[tool.poetry]
name = "ws-sync"
version = "0.6.10"
description = "Keep objects synchronized over a persistent WebSocket session"
authors = ["Joong-Won Seo <joong.won.seo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
starlette = ">=0.37.2"
jsonpatch = "^1.33"
pydantic = "^2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-asyncio = "^1.0.0"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
